# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: trusty
sudo: false
cache: packages
env:
  global:
    - NOT_CRAN=true
    - _R_CHECK_FORCE_SUGGESTS_=false
script:
  - |
    R CMD build .
    travis_wait 45 R CMD check --no-build-vignettes --no-manual cloudml*tar.gz
    cd tests
    Rscript ../.travis.R

after_failure:
  - |
    cd tests
    travis_wait 45 Rscript ../.travis.R
    sleep 2
notifications:
  email:
    recipients:
      - javier@rstudio.com
    on_success: never
    on_failure: always
